apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JULIET-JULIET632/enterprise-k8s-platform.git
    targetRevision: main
    path: apps/demo
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
