apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: demo-error-rate
spec:
  metrics:
    - name: prometheus-test
      interval: 10s
      count: 3
      successCondition: result[0] > 0
      failureLimit: 1
      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
          query: |
            sum(up)
