apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: demo-error-rate
  namespace: default
spec:
  metrics:
    - name: error-rate
      interval: 10s
      count: 3
      failureLimit: 1
      successCondition: result[0] < 0.01
      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
          query: |
            (
              sum(rate(http_requests_total{job="demo",status_code=~"5.."}[1m]))
              /
              sum(rate(http_requests_total{job="demo"}[1m]))
            )
            or vector(0)
